# Generated by Django 4.2.29 on 2026-06-10 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoragePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(choices=[('area', 'Площадка'), ('container', 'Контейнер'), ('rack', 'Стелаж'), ('shelf', 'Полка'), ('box', 'Коробка')], max_length=20, verbose_name='Тип місця зберігання')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Код')),
                ('address', models.CharField(editable=False, max_length=255, unique=True, verbose_name='Адреса')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Назва')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активне')),
                ('is_default', models.BooleanField(default=False, verbose_name='За замовчуванням')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_places', to='storage.storagelocation', verbose_name='Локація')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='storage.storageplace', verbose_name='Батьківське місце зберігання')),
            ],
            options={
                'verbose_name': 'Місце зберігання',
                'verbose_name_plural': 'Місця зберігання',
                'db_table': 'storage_places',
                'ordering': ['place_type', 'code', 'id'],
            },
        ),
    ]
