# Generated by Django 4.2.29 on 2026-06-10 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0002_storageplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoragePlaceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Створено'), ('moved', 'Переміщено'), ('activated', 'Активовано'), ('deactivated', 'Деактивовано'), ('default_changed', 'Змінено місце за замовчуванням')], max_length=30, verbose_name='Тип події')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Дані події')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_place_events', to=settings.AUTH_USER_MODEL, verbose_name='Хто створив')),
                ('storage_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='storage.storageplace', verbose_name='Місце зберігання')),
            ],
            options={
                'verbose_name': 'Подія місця зберігання',
                'verbose_name_plural': 'Події місць зберігання',
                'db_table': 'storage_place_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
