# Generated by Django 4.2.29 on 2026-06-10 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_storageplaceevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageplace',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_places', to='storage.storagelocation', verbose_name='Локація'),
        ),
    ]
