# Generated by Django 4.2.29 on 2026-06-10 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_productattachment_is_primary_image'),
        ('storage', '0005_alter_storageplaceevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoragePlacePreferredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='preferred_storage_place', to='inventory.invitem', verbose_name='Номенклатура')),
                ('storage_place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preferred_items', to='storage.storageplace', verbose_name='Місце зберігання')),
            ],
            options={
                'verbose_name': 'Бажана номенклатура місця зберігання',
                'verbose_name_plural': 'Бажані номенклатури місць зберігання',
                'db_table': 'storage_place_preferred_items',
                'ordering': ['storage_place', 'inv_item'],
            },
        ),
        migrations.AddConstraint(
            model_name='storageplacepreferreditem',
            constraint=models.UniqueConstraint(fields=('storage_place', 'inv_item'), name='uq_storage_place_preferred_item_place_item'),
        ),
    ]
