# Generated by Django 4.2.29 on 2026-06-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_storageplacepreferreditem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageplaceevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Створено'), ('edited', 'Відредаговано'), ('moved', 'Переміщено'), ('activated', 'Активовано'), ('deactivated', 'Деактивовано'), ('default_changed', 'Змінено місце за замовчуванням'), ('preferred_items_changed', 'Змінено бажані номенклатури')], max_length=30, verbose_name='Тип події'),
        ),
    ]
