# Generated by Django 4.2.29 on 2026-06-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_storageplaceevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageplace',
            name='address_verbose',
            field=models.CharField(blank=True, editable=False, max_length=500, verbose_name='Повна адреса'),
        ),
        migrations.AddField(
            model_name='storageplace',
            name='root_location',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='all_storage_places', to='storage.storagelocation', verbose_name='Коренева локація'),
        ),
    ]
