# Generated by Django 4.2.29 on 2026-04-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=1, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адреса')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Локація складу',
                'verbose_name_plural': 'Локації складу',
                'db_table': 'warehouse_locations',
                'ordering': ['code', 'id'],
            },
        ),
    ]
