# Generated by Django 4.2.29 on 2026-04-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStoragePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(choices=[('container', 'Контейнер'), ('rack', 'Стелаж'), ('box', 'Бокс')], max_length=20, verbose_name='Тип місця зберігання')),
                ('code', models.CharField(editable=False, max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Назва')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('qr_code', models.CharField(editable=False, max_length=100, unique=True, verbose_name='QR код')),
                ('image', models.ImageField(blank=True, null=True, upload_to='warehouse/storage_places/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_places', to='warehouse.warehouselocation', verbose_name='Локація')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='warehouse.warehousestorageplace', verbose_name='Батьківське місце зберігання')),
            ],
            options={
                'verbose_name': 'Місце зберігання',
                'verbose_name_plural': 'Місця зберігання',
                'db_table': 'warehouse_storage_places',
                'ordering': ['place_type', 'code', 'id'],
            },
        ),
    ]
