# Generated by Django 4.2.29 on 2026-04-16 12:06

from django.db import migrations, models
import warehouse.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehousestorageplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousestorageplace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=warehouse.models.storage_place_image_upload_to, verbose_name='Фото'),
        ),
    ]
