# Generated by Django 4.2.29 on 2026-04-16 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_invitem_requires_storage_place'),
        ('orders', '0011_externalreceiptdocument_completed_and_more'),
        ('warehouse', '0003_alter_warehousestorageplace_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кількість')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_units', to='inventory.invitem', verbose_name='Номенклатурна позиція')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_units', to='warehouse.warehouselocation', verbose_name='Локація')),
                ('source_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_units', to='orders.externalorderitem', verbose_name='Джерело рядка замовлення')),
                ('source_receipt_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_units', to='orders.externalreceiptitem', verbose_name='Джерело приходу')),
                ('storage_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_units', to='warehouse.warehousestorageplace', verbose_name='Місце зберігання')),
            ],
            options={
                'verbose_name': 'Складська одиниця',
                'verbose_name_plural': 'Складські одиниці',
                'db_table': 'warehouse_units',
                'ordering': ['inventory_item__name', 'id'],
            },
        ),
    ]
