# Generated by Django 4.2.29 on 2026-04-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_warehouseunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouselocation',
            name='code',
            field=models.CharField(editable=False, max_length=3, verbose_name='Код'),
        ),
        migrations.AddConstraint(
            model_name='warehousestorageplace',
            constraint=models.UniqueConstraint(fields=('place_type', 'code'), name='uq_warehouse_storage_place_type_code'),
        ),
    ]
