# Generated by Django 4.2.29 on 2026-04-20 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0005_alter_warehouselocation_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseUnitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('intake', 'Первинна прийомка'), ('move', 'Переміщення'), ('split_move', 'Переміщення з розділенням')], max_length=20, verbose_name='Тип операції')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кількість')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_unit_events', to=settings.AUTH_USER_MODEL, verbose_name='Хто створив')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_events_from_location', to='warehouse.warehouselocation', verbose_name='Звідки: локація')),
                ('from_storage_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_events_from_storage_place', to='warehouse.warehousestorageplace', verbose_name='Звідки: місце зберігання')),
                ('result_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_events', to='warehouse.warehouseunit', verbose_name='Результуюча складська одиниця')),
                ('source_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_events', to='warehouse.warehouseunit', verbose_name='Вихідна складська одиниця')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_events_to_location', to='warehouse.warehouselocation', verbose_name='Куди: локація')),
                ('to_storage_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_events_to_storage_place', to='warehouse.warehousestorageplace', verbose_name='Куди: місце зберігання')),
            ],
            options={
                'verbose_name': 'Подія складської одиниці',
                'verbose_name_plural': 'Події складських одиниць',
                'db_table': 'warehouse_unit_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
