# Generated by Django 4.2.29 on 2026-04-22 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_tollingorder_tollingorderitem_tollingreceiptdocument_and_more'),
        ('warehouse', '0006_warehouseunitevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseunit',
            name='tolling_source_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_units', to='orders.tollingorderitem', verbose_name='Джерело рядка замовлення (давальницька схема)'),
        ),
        migrations.AddField(
            model_name='warehouseunit',
            name='tolling_source_receipt_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_units', to='orders.tollingreceiptitem', verbose_name='Джерело приходу (давальницька схема)'),
        ),
        migrations.AlterField(
            model_name='warehouseunit',
            name='source_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_units', to='orders.externalorderitem', verbose_name='Джерело рядка замовлення'),
        ),
        migrations.AlterField(
            model_name='warehouseunit',
            name='source_receipt_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_units', to='orders.externalreceiptitem', verbose_name='Джерело приходу'),
        ),
    ]
