# Generated by Django 4.2.29 on 2026-04-24 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0012_tollingorder_tollingorderitem_tollingreceiptdocument_and_more'),
        ('warehouse', '0007_warehouseunit_tolling_source_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseunitevent',
            name='operation_type',
            field=models.CharField(choices=[('intake', 'Первинна прийомка'), ('converted_intake', 'Первинна прийомка з конвертацією'), ('move', 'Переміщення'), ('split_move', 'Переміщення з розділенням')], max_length=20, verbose_name='Тип операції'),
        ),
        migrations.CreateModel(
            name='WarehouseReceiptItemConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кількість у документах постачальника')),
                ('target_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кількість у складських одиницях')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_receipt_item_conversions', to=settings.AUTH_USER_MODEL, verbose_name='Хто створив')),
                ('receipt_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_conversion', to='orders.externalreceiptitem', verbose_name='Рядок приходу')),
            ],
            options={
                'verbose_name': 'Конвертація рядка приходу',
                'verbose_name_plural': 'Конвертації рядків приходу',
                'db_table': 'warehouse_receipt_item_conversions',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
