# Generated by Django 4.2.29 on 2026-04-26 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0008_alter_warehouseunitevent_operation_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('active', 'Активний'), ('executed', 'Виконаний'), ('cancelled', 'Скасований')], default='draft', max_length=20)),
                ('planned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_plans', to=settings.AUTH_USER_MODEL)),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_plans', to='warehouse.warehouselocation')),
                ('target_storage_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_plans', to='warehouse.warehousestorageplace')),
            ],
            options={
                'db_table': 'warehouse_movement_plans',
            },
        ),
        migrations.CreateModel(
            name='MovementPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('move_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('remainder_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('requires_split', models.BooleanField(default=False)),
                ('is_reserved', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.movementplan')),
                ('warehouse_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movement_plan_items', to='warehouse.warehouseunit')),
            ],
            options={
                'db_table': 'warehouse_movement_plan_items',
            },
        ),
        migrations.AddConstraint(
            model_name='movementplanitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reserved', True)), fields=('warehouse_unit',), name='uq_reserved_movement_plan_unit'),
        ),
    ]
