# Generated by Django 4.2.29 on 2026-04-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_movementplan_movementplanitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementplan',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
