# Generated by Django 4.2.29 on 2026-04-29 14:27

from django.db import migrations, models
import warehouse.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_movementplan_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementplan',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to=warehouse.models.movement_plan_invoice_upload_to),
        ),
        migrations.AddField(
            model_name='movementplan',
            name='invoice_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movementplan',
            name='invoice_snapshot_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
