# Generated by Django 4.2.29 on 2026-04-30 16:09

from django.db import migrations, models
import warehouse.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_movementplan_invoice_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousestorageplace',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='warehousestorageplace',
            name='qr_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=warehouse.models.storage_place_qr_pdf_upload_to, verbose_name='QR PDF'),
        ),
    ]
