# Generated by Django 4.2.29 on 2026-05-01 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_remove_warehousestorageplace_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementplanitem',
            name='executed_source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executed_movement_plan_items_from_location', to='warehouse.warehouselocation'),
        ),
        migrations.AddField(
            model_name='movementplanitem',
            name='executed_source_location_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='movementplanitem',
            name='executed_source_location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movementplanitem',
            name='executed_source_storage_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executed_movement_plan_items_from_storage_place', to='warehouse.warehousestorageplace'),
        ),
        migrations.AddField(
            model_name='movementplanitem',
            name='executed_source_storage_place_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='movementplanitem',
            name='executed_source_storage_place_display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movementplanitem',
            name='executed_source_storage_place_full_display',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
