# Generated by Django 4.2.29 on 2026-05-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_movementplanitem_executed_source_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseunit',
            name='status',
            field=models.CharField(choices=[('on_stock', 'На складі'), ('in_production', 'У виробництві'), ('consumed', 'Використано'), ('written_off', 'Списано'), ('returned', 'Повернено'), ('blocked', 'Заблоковано')], default='on_stock', max_length=20, verbose_name='Статус'),
        ),
    ]
