# Generated by Django 4.2.29 on 2026-05-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_warehouseunit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseunit',
            name='is_active',
        ),
    ]
