# Generated by Django 4.2.29 on 2026-05-06 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0007_salesordercomponent_uq_sales_order_component_sales_order_inv_item'),
        ('warehouse', '0015_remove_warehouseunit_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProductionReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Зарезервовано'), ('transferred', 'Передано у виробництво'), ('cancelled', 'Скасовано')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_production_reservations', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_production_reservations', to='sales.salesorder')),
                ('sales_order_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_production_reservations', to='sales.salesordercomponent')),
                ('warehouse_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_reservations', to='warehouse.warehouseunit')),
            ],
            options={
                'db_table': 'warehouse_production_reservations',
                'ordering': ['sales_order', 'sales_order_component', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouseproductionreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('warehouse_unit',), name='uq_active_production_reservation_unit'),
        ),
    ]
