# Generated by Django 4.2.29 on 2026-05-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_salesordercomponent_uq_sales_order_component_sales_order_inv_item'),
        ('organizations', '0004_person_rank_person_rank_force_type'),
        ('inventory', '0010_invitem_is_required_for_production_start_and_more'),
        ('warehouse', '0016_warehouseproductionreservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseSalesOrderShortage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment_mode', models.CharField(choices=[('customer', 'Від замовника'), ('mixed', 'Комбіновано')], max_length=20)),
                ('missing_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('is_required_for_start', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('inv_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_sales_order_shortages', to='inventory.invitem')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_sales_order_shortages', to='organizations.organization')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_shortages', to='sales.salesorder')),
                ('sales_order_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_shortages', to='sales.salesordercomponent')),
            ],
            options={
                'db_table': 'warehouse_sales_order_shortages',
                'ordering': ['sales_order', 'sales_order_component', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='warehousesalesordershortage',
            constraint=models.UniqueConstraint(fields=('sales_order_component',), name='uq_warehouse_sales_order_shortage_component'),
        ),
    ]
