# Generated by Django 4.2.29 on 2026-05-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_invitem_is_required_for_production_start'),
        ('warehouse', '0018_remove_warehousesalesordershortage_is_required_for_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehousesalesordershortage',
            options={'ordering': ['inv_item__name', 'inv_item_id']},
        ),
        migrations.RemoveConstraint(
            model_name='warehousesalesordershortage',
            name='uq_warehouse_sales_order_shortage_component',
        ),
        migrations.RenameField(
            model_name='warehousesalesordershortage',
            old_name='last_checked_at',
            new_name='last_recalculated_at',
        ),
        migrations.RemoveField(
            model_name='warehousesalesordershortage',
            name='fulfillment_mode',
        ),
        migrations.RemoveField(
            model_name='warehousesalesordershortage',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='warehousesalesordershortage',
            name='sales_order',
        ),
        migrations.RemoveField(
            model_name='warehousesalesordershortage',
            name='sales_order_component',
        ),
        migrations.AddField(
            model_name='warehousesalesordershortage',
            name='available_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehousesalesordershortage',
            name='required_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehousesalesordershortage',
            name='inv_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_sales_order_shortage', to='inventory.invitem'),
        ),
    ]
