# Generated by Django 4.2.29 on 2026-05-18 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_productiondiaryentry_productiondiaryattachment'),
        ('warehouse', '0019_alter_warehousesalesordershortage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproductionreservation',
            name='production_order_step_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_production_reservations', to='production.productionorderstepcomponent'),
        ),
    ]
