# Generated by Django 4.2.29 on 2026-05-19 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import warehouse.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_invitem_is_required_for_production_start'),
        ('production', '0005_productiondiaryentry_productiondiaryattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0020_warehouseproductionreservation_production_order_step_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseProductionMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Створено'), ('executed', 'Виконано'), ('cancelled', 'Скасовано')], default='created', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to=warehouse.models.production_movement_invoice_upload_to)),
                ('invoice_generated_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_snapshot_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_production_movements', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_production_movements', to='production.productionorder')),
                ('production_order_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_production_movements', to='production.productionorderstep')),
            ],
            options={
                'db_table': 'warehouse_production_movements',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AlterField(
            model_name='warehouseunitevent',
            name='operation_type',
            field=models.CharField(choices=[('intake', 'Первинна прийомка'), ('converted_intake', 'Первинна прийомка з конвертацією'), ('move', 'Переміщення'), ('split_move', 'Переміщення з розділенням'), ('production_transfer', 'Передача у виробництво')], max_length=20, verbose_name='Тип операції'),
        ),
        migrations.CreateModel(
            name='WarehouseProductionMovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('executed_source_location_code', models.CharField(blank=True, max_length=3)),
                ('executed_source_location_name', models.CharField(blank=True, max_length=255)),
                ('executed_source_storage_place_code', models.CharField(blank=True, max_length=3)),
                ('executed_source_storage_place_display_name', models.CharField(blank=True, max_length=255)),
                ('executed_source_storage_place_full_display', models.CharField(blank=True, max_length=500)),
                ('executed_source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_movement_items_from_location', to='warehouse.warehouselocation')),
                ('executed_source_storage_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_movement_items_from_storage_place', to='warehouse.warehousestorageplace')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_movement_items', to='inventory.invitem')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.warehouseproductionmovement')),
                ('production_reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_movement_items', to='warehouse.warehouseproductionreservation')),
                ('result_warehouse_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_movement_result_items', to='warehouse.warehouseunit')),
                ('source_warehouse_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_movement_source_items', to='warehouse.warehouseunit')),
            ],
            options={
                'db_table': 'warehouse_production_movement_items',
                'ordering': ['movement', 'inventory_item', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouseproductionmovementitem',
            constraint=models.UniqueConstraint(fields=('production_reservation',), name='uq_production_movement_item_reservation'),
        ),
        migrations.AddConstraint(
            model_name='warehouseproductionmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'created')), fields=('production_order_step',), name='uq_created_production_movement_step'),
        ),
    ]
