# Generated by Django 4.2.29 on 2026-05-26 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0021_warehouseproductionmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproductionmovement',
            name='issue_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouseproductionmovement',
            name='issue_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseproductionmovement',
            name='issue_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_warehouse_production_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehouseunitevent',
            name='operation_type',
            field=models.CharField(choices=[('intake', 'Первинна прийомка'), ('converted_intake', 'Первинна прийомка з конвертацією'), ('move', 'Переміщення'), ('split_move', 'Переміщення з розділенням'), ('production_transfer', 'Передача у виробництво'), ('production_consume', 'Використання у виробництві')], max_length=20, verbose_name='Тип операції'),
        ),
    ]
