# Generated by Django 4.2.29 on 2026-05-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_warehouseproductionmovement_issue_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseunitevent',
            name='operation_type',
            field=models.CharField(choices=[('intake', 'Первинна прийомка'), ('converted_intake', 'Первинна прийомка з конвертацією'), ('move', 'Переміщення'), ('split_move', 'Переміщення з розділенням'), ('production_transfer', 'Передача у виробництво'), ('production_consume', 'Використання у виробництві'), ('reclamation_return', 'Повернення постачальнику')], max_length=20, verbose_name='Тип операції'),
        ),
    ]
