# Generated by Django 4.2.29 on 2026-04-21 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0005_taxtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Юридична назва')),
                ('type', models.CharField(choices=[('military', 'Military'), ('commercial', 'Commercial'), ('charity', 'Charity'), ('vendor', 'Vendor')], max_length=32, verbose_name='Тип організації')),
                ('edrpou', models.CharField(max_length=20, verbose_name='ЄДРПОУ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Діюча')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MilitaryOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_code', models.CharField(blank=True, help_text='Або одна літера і 4 цифри, або 4 цифри', max_length=5, verbose_name='A-код')),
                ('military_type', models.CharField(choices=[('zsu', 'ЗСУ'), ('ngu', 'НГУ'), ('dpsu', 'ДПСУ'), ('dsns', 'ДСНС'), ('mvs', 'МВС'), ('sbu', 'СБУ')], max_length=20, verbose_name='Тип військової організації')),
                ('military_branch', models.CharField(blank=True, choices=[('sv', 'СВ'), ('ps', 'ПС'), ('vms', 'ВМС'), ('dshv', 'ДШВ'), ('sbs', 'СБС'), ('sp', 'СП'), ('sl', 'СЛ'), ('gur', 'ГУР'), ('sso', 'ССО'), ('tro', 'ТРО'), ('kms', 'КМС')], max_length=20, verbose_name='Рід / вид військ')),
                ('military_corps', models.CharField(blank=True, choices=[('1_nsu_azov', '1-й корпус НГУ «Азов»'), ('2_nsu_khartiia', '2-й корпус НГУ «Хартія»'), ('3_ak', '3-й армійський корпус'), ('7_dshv', '7-й корпус ДШВ'), ('8_dshv', '8-й корпус ДШВ'), ('9_ak', '9-й армійський корпус'), ('10_ak', '10-й армійський корпус'), ('11_ak', '11-й армійський корпус'), ('12_ak', '12-й армійський корпус'), ('14_ak', '14-й армійський корпус'), ('15_ak', '15-й армійський корпус'), ('16_ak', '16-й армійський корпус'), ('17_ak', '17-й армійський корпус'), ('18_ak', '18-й армійський корпус'), ('19_ak', '19-й армійський корпус'), ('20_ak', '20-й армійський корпус'), ('21_ak', '21-й армійський корпус'), ('30_marine_corps', '30-й корпус морської піхоти')], max_length=32, verbose_name='Корпус')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='military_profile', to='organizations.organization', verbose_name='Організація')),
            ],
            options={
                'verbose_name': 'Military organization profile',
                'verbose_name_plural': 'Military organization profiles',
            },
        ),
        migrations.CreateModel(
            name='CommercialOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipn', models.CharField(max_length=20, verbose_name='ІПН')),
                ('legal_address', models.TextField(verbose_name='Юридична адреса')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_profile', to='organizations.organization', verbose_name='Організація')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.taxtype', verbose_name='Форма оподаткування')),
            ],
            options={
                'verbose_name': 'Commercial organization profile',
                'verbose_name_plural': 'Commercial organization profiles',
            },
        ),
        migrations.CreateModel(
            name='CharityOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_address', models.TextField(verbose_name='Юридична адреса')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charity_profile', to='organizations.organization', verbose_name='Організація')),
            ],
            options={
                'verbose_name': 'Charity organization profile',
                'verbose_name_plural': 'Charity organization profiles',
            },
        ),
    ]
