# Generated by Django 4.2.29 on 2026-04-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='edrpou',
            field=models.CharField(max_length=20, unique=True, verbose_name='ЄДРПОУ'),
        ),
        migrations.AddConstraint(
            model_name='militaryorganization',
            constraint=models.UniqueConstraint(condition=models.Q(('a_code', ''), _negated=True), fields=('a_code',), name='uq_military_organization_a_code'),
        ),
    ]
