# Generated by Django 4.2.29 on 2026-05-05 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_edrpou_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва посади')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('middle_name', models.CharField(blank=True, max_length=255, verbose_name='По батькові')),
                ('birth_day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='День народження')),
                ('birth_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Місяць народження')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рік народження')),
                ('phone_1_type', models.CharField(blank=True, choices=[('voice', 'Voice'), ('whatsapp', 'WhatsApp'), ('signal', 'Signal'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('other', 'Other')], max_length=20, verbose_name='Тип комунікації 1')),
                ('phone_1', models.CharField(blank=True, max_length=50, verbose_name='Телефон 1')),
                ('phone_2_type', models.CharField(blank=True, choices=[('voice', 'Voice'), ('whatsapp', 'WhatsApp'), ('signal', 'Signal'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('other', 'Other')], max_length=20, verbose_name='Тип комунікації 2')),
                ('phone_2', models.CharField(blank=True, max_length=50, verbose_name='Телефон 2')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'middle_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationPersonAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True, verbose_name='Поточне призначення')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_assignments', to='organizations.organization', verbose_name='Організація')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_assignments', to='organizations.person', verbose_name='Людина')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_assignments', to='organizations.organizationposition', verbose_name='Посада')),
            ],
            options={
                'ordering': ['organization__name', 'position__name', 'person__last_name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='organizationpersonassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('person',), name='uq_person_single_current_assignment'),
        ),
        migrations.AddConstraint(
            model_name='organizationpersonassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('organization', 'position'), name='uq_organization_position_single_current_person'),
        ),
    ]
