# Generated by Django 4.2.29 on 2026-05-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationposition_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='rank',
            field=models.CharField(blank=True, choices=[('soldier', 'Солдат'), ('senior_soldier', 'Старший солдат'), ('junior_sergeant', 'Молодший сержант'), ('sergeant', 'Сержант'), ('senior_sergeant', 'Старший сержант'), ('chief_sergeant', 'Головний сержант'), ('staff_sergeant', 'Штаб-сержант'), ('master_sergeant', 'Майстер-сержант'), ('senior_master_sergeant', 'Старший майстер-сержант'), ('chief_master_sergeant', 'Головний майстер-сержант'), ('matros', 'Матрос'), ('senior_matros', 'Старший матрос'), ('starshyna_2', 'Старшина 2 статті'), ('starshyna_1', 'Старшина 1 статті'), ('chief_starshyna', 'Головний старшина'), ('chief_ship_starshyna', 'Головний корабельний старшина'), ('staff_starshyna', 'Штаб-старшина'), ('master_starshyna', 'Майстер-старшина'), ('senior_master_starshyna', 'Старший майстер-старшина'), ('chief_master_starshyna', 'Головний майстер-старшина'), ('junior_lieutenant', 'Молодший лейтенант'), ('lieutenant', 'Лейтенант'), ('senior_lieutenant', 'Старший лейтенант'), ('captain', 'Капітан'), ('captain_lieutenant', 'Капітан-лейтенант'), ('major', 'Майор'), ('captain_3_rank', 'Капітан 3 рангу'), ('lieutenant_colonel', 'Підполковник'), ('captain_2_rank', 'Капітан 2 рангу'), ('colonel', 'Полковник'), ('captain_1_rank', 'Капітан 1 рангу'), ('brigadier_general', 'Бригадний генерал'), ('commodore', 'Коммодор'), ('major_general', 'Генерал-майор'), ('rear_admiral', 'Контр-адмірал'), ('lieutenant_general', 'Генерал-лейтенант'), ('vice_admiral', 'Віце-адмірал'), ('general', 'Генерал'), ('admiral', 'Адмірал')], max_length=50, verbose_name='Звання'),
        ),
        migrations.AddField(
            model_name='person',
            name='rank_force_type',
            field=models.CharField(blank=True, choices=[('land', 'Land'), ('navy', 'Navy')], max_length=10, verbose_name='Тип звань'),
        ),
    ]
