# Generated by Django 4.2.29 on 2026-05-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0009_remove_salesordercomponent_is_required_for_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('in_progress', 'В роботі'), ('ready', 'Готово'), ('cancelled', 'Скасовано')], default='draft', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('use_work_tracking', models.BooleanField(default=False)),
                ('use_hr_tracking', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('sales_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='production_order', to='sales.salesorder')),
            ],
            options={
                'db_table': 'production_orders',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
