# Generated by Django 4.2.29 on 2026-05-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_invitem_is_required_for_production_start'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sequence_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('confirmed', 'Підтверджено'), ('in_progress', 'В роботі'), ('finished', 'Завершено'), ('cancelled', 'Скасовано')], default='draft', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.productionorder')),
                ('source_product_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_order_steps', to='inventory.productstep')),
            ],
            options={
                'db_table': 'production_order_steps',
                'ordering': ['production_order', 'sequence_number', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productionorderstep',
            constraint=models.UniqueConstraint(fields=('production_order', 'sequence_number'), name='uq_production_order_step_sequence'),
        ),
        migrations.AddConstraint(
            model_name='productionorderstep',
            constraint=models.UniqueConstraint(fields=('production_order', 'source_product_step'), name='uq_production_order_step_source_product_step'),
        ),
    ]
