# Generated by Django 4.2.29 on 2026-05-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_invitem_is_required_for_production_start'),
        ('sales', '0009_remove_salesordercomponent_is_required_for_start'),
        ('production', '0002_productionorderstep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrderStepComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inv_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_order_step_components', to='inventory.invitem')),
                ('production_order_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='production.productionorderstep')),
                ('sales_order_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_order_step_components', to='sales.salesordercomponent')),
                ('source_product_step_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_order_step_components', to='inventory.productstepitem')),
            ],
            options={
                'db_table': 'production_order_step_components',
                'ordering': ['production_order_step', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productionorderstepcomponent',
            constraint=models.UniqueConstraint(fields=('production_order_step', 'source_product_step_item'), name='uq_production_step_component_source_item'),
        ),
    ]
