# Generated by Django 4.2.29 on 2026-05-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionorderstepcomponent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorderstepcomponent',
            name='is_required_for_step_start',
            field=models.BooleanField(default=True),
        ),
    ]
