# Generated by Django 4.2.29 on 2026-05-13 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import production.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0004_productionorderstepcomponent_is_required_for_step_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_diary_entries', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='production.productionorder')),
                ('production_order_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to='production.productionorderstep')),
            ],
            options={
                'db_table': 'production_diary_entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionDiaryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=production.models.production_diary_attachment_upload_to)),
                ('attachment_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Відео'), ('other', 'Інше')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='production.productiondiaryentry')),
            ],
            options={
                'db_table': 'production_diary_attachments',
                'ordering': ['entry', 'id'],
            },
        ),
    ]
