# Generated by Django 4.2.29 on 2026-05-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_productiondiaryentry_productiondiaryattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='expected_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorderstep',
            name='expected_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
