# Generated by Django 4.2.29 on 2026-06-08 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_externalrefunddocument_file'),
        ('warehouse', '0023_alter_warehouseunitevent_operation_type'),
        ('inventory', '0018_productattachment_is_primary_image'),
        ('production', '0006_productionorder_expected_ready_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrderMaterialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('processing', 'Обробляється'), ('completed', 'Завершено'), ('failed', 'Помилка')], default='pending', max_length=20)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_snapshot', to='production.productionorder')),
            ],
            options={
                'db_table': 'production_order_material_snapshots',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderMaterialSnapshotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('origin_type', models.CharField(choices=[('own', 'Закупівля'), ('customer', 'Замовник'), ('donor', 'Донор')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inv_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_material_snapshot_items', to='inventory.invitem')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionordermaterialsnapshot')),
                ('source_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_snapshot_items', to='orders.externalorderitem')),
                ('source_receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_snapshot_items', to='orders.externalreceiptitem')),
                ('tolling_source_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_snapshot_items', to='orders.tollingorderitem')),
                ('tolling_source_receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_snapshot_items', to='orders.tollingreceiptitem')),
                ('warehouse_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_material_snapshot_items', to='warehouse.warehouseunit')),
            ],
            options={
                'db_table': 'production_order_material_snapshot_items',
                'ordering': ['snapshot', 'inv_item', 'id'],
            },
        ),
    ]
