# Generated by Django 4.2.29 on 2026-06-08 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_externalrefunddocument_file'),
        ('vendors', '0009_alter_vendor_logo'),
        ('production', '0007_productionordermaterialsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionordermaterialsnapshotitem',
            name='external_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_snapshot_items', to='orders.externalorder'),
        ),
        migrations.AddField(
            model_name='productionordermaterialsnapshotitem',
            name='external_order_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='productionordermaterialsnapshotitem',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_snapshot_items', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='productionordermaterialsnapshotitem',
            name='vendor_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_material_snapshot_items', to='vendors.vendoritem'),
        ),
        migrations.AddField(
            model_name='productionordermaterialsnapshotitem',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productionordermaterialsnapshotitem',
            name='vendor_sku',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
