# Generated by Django 4.2.29 on 2026-06-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_productionordermaterialsnapshotitem_external_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionordermaterialsnapshotitem',
            name='cost_with_vat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='productionordermaterialsnapshotitem',
            name='cost_without_vat',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='productionordermaterialsnapshotitem',
            name='prices_include_vat',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionordermaterialsnapshotitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='productionordermaterialsnapshotitem',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='productionordermaterialsnapshotitem',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
