# Generated by Django 4.2.29 on 2026-03-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Бренд')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Країна')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Код')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
        ),
    ]
