# Generated by Django 4.2.29 on 2026-03-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_alter_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Статус зовнішнього замовлення',
                'verbose_name_plural': 'Статуси зовнішнього замовлення',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
