# Generated by Django 4.2.29 on 2026-03-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_externalorderpaymentstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('is_vat_payer', models.BooleanField(default=False, verbose_name='Платник ПДВ')),
                ('is_profit_tax_payer', models.BooleanField(default=False, verbose_name='Платник податку на прибуток')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Система оподаткування',
                'verbose_name_plural': 'Системи оподаткування',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
