# Generated by Django 4.2.29 on 2026-04-02 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_invitem_created_at_alter_invitem_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('developer', models.CharField(choices=[('own', 'Власний'), ('external', 'Зовнішній')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'product_families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFamilyLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='product_family_library/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('attachment_type', models.CharField(choices=[('photo', 'Фотографія'), ('video', 'Відео'), ('drawing', 'Креслення'), ('documentation', 'Документація')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_family', models.ForeignKey(db_column='product_family_id', on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='inventory.productfamily')),
            ],
            options={
                'db_table': 'product_family_library',
                'ordering': ['name', 'id'],
            },
        ),
    ]
