# Generated by Django 4.2.29 on 2026-04-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productfamily_productfamilylibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_base_modification', models.BooleanField(default=False)),
                ('development_started_at', models.DateField()),
                ('development_finished_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_family', models.ForeignKey(db_column='product_family_id', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.productfamily')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['product_family__name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='ProductLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='product_library/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('attachment_type', models.CharField(choices=[('photo', 'Фотографія'), ('video', 'Відео'), ('drawing', 'Креслення'), ('documentation', 'Документація')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='inventory.product')),
            ],
            options={
                'db_table': 'product_library',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_family', 'version'), name='uq_product_family_version'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_base_modification', True)), fields=('product_family',), name='uq_product_family_single_base_modification'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('development_finished_at__gte', models.F('development_started_at'))), name='chk_product_development_dates_order'),
        ),
    ]
