# Generated by Django 4.2.29 on 2026-04-02 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_productlibrary_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='chk_product_development_dates_order',
        ),
    ]
