# Generated by Django 4.2.29 on 2026-04-02 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_productlibrary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='inventory.product')),
            ],
            options={
                'db_table': 'product_steps',
                'ordering': ['product', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductStepLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='product_step_library/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('attachment_type', models.CharField(choices=[('photo', 'Фотографія'), ('video', 'Відео'), ('drawing', 'Креслення'), ('documentation', 'Документація')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_step', models.ForeignKey(db_column='product_step_id', on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to='inventory.productstep')),
            ],
            options={
                'db_table': 'product_step_library',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductStepItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inv_item', models.ForeignKey(db_column='inv_item_id', on_delete=django.db.models.deletion.PROTECT, related_name='product_step_items', to='inventory.invitem')),
                ('product_step', models.ForeignKey(db_column='product_step_id', on_delete=django.db.models.deletion.CASCADE, related_name='step_items', to='inventory.productstep')),
            ],
            options={
                'db_table': 'product_step_items',
                'ordering': ['product_step', 'inv_item'],
            },
        ),
        migrations.AddConstraint(
            model_name='productstepitem',
            constraint=models.UniqueConstraint(fields=('product_step', 'inv_item'), name='uq_product_step_item_product_step_inv_item'),
        ),
        migrations.AddConstraint(
            model_name='productstep',
            constraint=models.UniqueConstraint(fields=('product', 'sort_order'), name='uq_product_step_product_sort_order'),
        ),
        migrations.AddConstraint(
            model_name='productstep',
            constraint=models.UniqueConstraint(fields=('product', 'name'), name='uq_product_step_product_name'),
        ),
    ]
