# Generated by Django 4.2.29 on 2026-04-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_productstep_productsteplibrary_productstepitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstep',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
