# Generated by Django 4.2.29 on 2026-04-16 12:06

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productstep_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitem',
            name='image',
            field=models.ImageField(blank=True, db_column='image_path', null=True, upload_to=inventory.models.inv_item_image_upload_to),
        ),
    ]
