# Generated by Django 4.2.29 on 2026-04-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_invitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitem',
            name='requires_storage_place',
            field=models.BooleanField(default=True),
        ),
    ]
