# Generated by Django 4.2.29 on 2026-04-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_invitem_requires_storage_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitem',
            name='is_splittable',
            field=models.BooleanField(default=False),
        ),
    ]
