# Generated by Django 4.2.29 on 2026-05-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_invitem_is_splittable'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitem',
            name='is_required_for_production_start',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invitem',
            name='is_required_for_step_start',
            field=models.BooleanField(default=True),
        ),
    ]
