# Generated by Django 4.2.29 on 2026-05-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_invitem_is_required_for_production_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitem',
            name='is_required_for_production_start',
        ),
    ]
