# Generated by Django 4.2.29 on 2026-05-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_invitem_is_required_for_production_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='development_status',
            field=models.CharField(choices=[('in_development', 'В розробці'), ('finished', 'Завершено')], default='in_development', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='development_finished_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
