# Generated by Django 4.2.29 on 2026-05-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_development_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hr_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='work_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='development_status',
            field=models.CharField(choices=[('in_development', 'В розробці'), ('finished', 'Розробку завершено')], default='in_development', max_length=30),
        ),
    ]
