# Generated by Django 4.2.29 on 2026-05-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_product_development_status_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('development_finished_at__isnull', True), ('development_status', 'in_development')), models.Q(('development_finished_at__gte', models.F('development_started_at')), ('development_finished_at__isnull', False), ('development_status', 'finished')), _connector='OR'), name='ck_product_development_status_dates'),
        ),
    ]
