# Generated by Django 4.2.29 on 2026-05-29 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_product_hr_tracking_product_work_tracking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_step', models.ForeignKey(db_column='product_step_id', on_delete=django.db.models.deletion.CASCADE, related_name='works', to='inventory.productstep')),
            ],
            options={
                'db_table': 'product_works',
                'ordering': ['product_step', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductWorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inv_item', models.ForeignKey(db_column='inv_item_id', on_delete=django.db.models.deletion.PROTECT, related_name='product_work_items', to='inventory.invitem')),
                ('product_work', models.ForeignKey(db_column='product_work_id', on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='inventory.productwork')),
            ],
            options={
                'db_table': 'product_work_items',
                'ordering': ['product_work', 'inv_item'],
            },
        ),
        migrations.AddConstraint(
            model_name='productworkitem',
            constraint=models.UniqueConstraint(fields=('product_work', 'inv_item'), name='uq_product_work_item_product_work_inv_item'),
        ),
        migrations.AddConstraint(
            model_name='productwork',
            constraint=models.UniqueConstraint(fields=('product_step', 'sort_order'), name='uq_product_work_product_step_sort_order'),
        ),
        migrations.AddConstraint(
            model_name='productwork',
            constraint=models.UniqueConstraint(fields=('product_step', 'name'), name='uq_product_work_product_step_name'),
        ),
    ]
