# Generated by Django 4.2.29 on 2026-06-03 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_productwork_productworkitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlibrary',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsteplibrary',
            name='product_step',
        ),
        migrations.DeleteModel(
            name='ProductFamilyLibrary',
        ),
        migrations.DeleteModel(
            name='ProductLibrary',
        ),
        migrations.DeleteModel(
            name='ProductStepLibrary',
        ),
    ]
