# Generated by Django 4.2.29 on 2026-06-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_productlibrary_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='product_attachments/')),
                ('attachment_type', models.CharField(choices=[('photo', 'Фотографія'), ('video', 'Відео'), ('document', 'Документ'), ('drawing', 'Креслення'), ('instruction', 'Інструкція'), ('other', 'Інше')], max_length=30)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.product')),
                ('product_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.productstep')),
                ('product_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.productwork')),
            ],
            options={
                'db_table': 'product_attachments',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
