# Generated by Django 4.2.29 on 2026-06-04 07:33

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_productattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattachment',
            name='display_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='file',
            field=models.FileField(upload_to=inventory.models.product_attachment_upload_to),
        ),
    ]
