# Generated by Django 4.2.29 on 2026-06-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_productattachment_display_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattachment',
            name='is_primary_image',
            field=models.BooleanField(default=False),
        ),
    ]
