# Generated by Django 4.2.29 on 2026-03-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('tax_type', models.CharField(choices=[('LLC_VAT', 'ТОВ / платник ПДВ'), ('LLC_NO_VAT', 'ТОВ / не платник ПДВ'), ('FOP_2', 'ФОП 2 група'), ('FOP_3', 'ФОП 3 група'), ('NON_PROFIT', 'Благодійна організація')], max_length=20)),
                ('edrpou', models.CharField(blank=True, max_length=20)),
                ('ipn', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_sku', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_items', to='inventory.invitem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_items', to='vendors.vendor')),
            ],
        ),
    ]
