# Generated by Django 4.2.29 on 2026-03-28 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoritem',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.brand', verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='vendoritem',
            name='country_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.country', verbose_name='Країна походження'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='edrpou',
            field=models.CharField(blank=True, max_length=20, verbose_name='ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Основний e-mail'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ipn',
            field=models.CharField(blank=True, max_length=20, verbose_name='ІПН'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Діючий'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Повна назва'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Основний телефон'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='tax_type',
            field=models.CharField(choices=[('LLC_VAT', 'ТОВ / платник ПДВ'), ('LLC_NO_VAT', 'ТОВ / не платник ПДВ'), ('FOP_2', 'ФОП 2 група'), ('FOP_3', 'ФОП 3 група'), ('NON_PROFIT', 'Благодійна організація')], max_length=20, verbose_name='Форма оподаткування'),
        ),
    ]
