# Generated by Django 4.2.29 on 2026-03-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_taxtype'),
        ('vendors', '0002_vendoritem_brand_vendoritem_country_of_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='tax_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.taxtype', verbose_name='Форма оподаткування'),
        ),
    ]
