# Generated by Django 4.2.29 on 2026-04-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoritem',
            name='name',
            field=models.CharField(default='temp', max_length=255, verbose_name='Назва постачальника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendoritem',
            name='vendor_sku',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='vendoritem',
            constraint=models.UniqueConstraint(fields=('vendor', 'vendor_sku'), name='uq_vendor_item_vendor_vendor_sku'),
        ),
    ]
