# Generated by Django 4.2.29 on 2026-04-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendoritem_name_alter_vendoritem_vendor_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
    ]
