# Generated by Django 4.2.29 on 2026-04-10 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendor_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Назва реквізитів')),
                ('iban', models.CharField(max_length=29, verbose_name='IBAN')),
                ('is_default', models.BooleanField(default=False, verbose_name='За замовчуванням')),
                ('is_active', models.BooleanField(default=True, verbose_name='Діючі')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_details', to='vendors.vendor', verbose_name='Постачальник')),
            ],
            options={
                'ordering': ['-is_default', 'label', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='vendorpaymentdetails',
            constraint=models.UniqueConstraint(fields=('vendor', 'iban'), name='uq_vendor_payment_details_vendor_iban'),
        ),
        migrations.AddConstraint(
            model_name='vendorpaymentdetails',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('vendor',), name='uq_vendor_payment_details_single_default'),
        ),
    ]
