# Generated by Django 4.2.29 on 2026-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_vendorpaymentdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='vat',
            field=models.BooleanField(default=False, verbose_name='Платник ПДВ'),
        ),
    ]
