# Generated by Django 4.2.29 on 2026-04-13 09:42

from django.db import migrations, models
import vendors.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_vendor_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=vendors.models.vendor_logo_upload_to, verbose_name='Логотип'),
        ),
    ]
