# Generated by Django 4.2.29 on 2026-03-28 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0003_alter_vendor_tax_type'),
        ('reference', '0005_taxtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='Номер замовлення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.externalorderpaymentstatus', verbose_name='Статус оплати')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.externalorderstatus', verbose_name='Статус')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vendors.vendor', verbose_name='Постачальник')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кількість')),
                ('agreed_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна (UAH)')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Термін поставки (днів)')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Очікувана дата поставки')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.externalorder', verbose_name='Замовлення')),
                ('vendor_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendors.vendoritem', verbose_name='Товар постачальника')),
            ],
        ),
    ]
