# Generated by Django 4.2.29 on 2026-04-07 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalReceiptDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=50, unique=True, verbose_name='Номер документа приходу')),
                ('receipt_date', models.DateField(verbose_name='Дата приходу')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_external_receipt_documents', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
            ],
            options={
                'db_table': 'external_receipt_documents',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='externalorder',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='externalorderitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='externalorder',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='externalorder',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='externalorderitem',
            name='is_active',
        ),
        migrations.AddField(
            model_name='externalorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Знижка'),
        ),
        migrations.AlterField(
            model_name='externalorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('in_progress', 'В роботі'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='externalorderitem',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ціна'),
        ),
        migrations.AlterModelTable(
            name='externalorder',
            table='external_orders',
        ),
        migrations.AlterModelTable(
            name='externalorderitem',
            table='external_order_items',
        ),
        migrations.CreateModel(
            name='ExternalReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Отримана кількість')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='orders.externalorderitem', verbose_name='Рядок замовлення')),
                ('receipt_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.externalreceiptdocument', verbose_name='Документ приходу')),
            ],
            options={
                'db_table': 'external_receipt_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='externalreceiptdocument',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_documents', to='orders.externalorder', verbose_name='Замовлення'),
        ),
        migrations.CreateModel(
            name='ExternalPaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(max_length=50, unique=True, verbose_name='Номер платіжного документа')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('approved', 'Погоджено'), ('paid', 'Оплачено'), ('cancelled', 'Скасовано')], default='draft', max_length=20, verbose_name='Статус')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сума оплати')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Дата оплати')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_external_payment_documents', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_documents', to='orders.externalorder', verbose_name='Замовлення')),
            ],
            options={
                'db_table': 'external_payment_documents',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
