# Generated by Django 4.2.29 on 2026-04-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_externalreceiptdocument_alter_externalorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalorderitem',
            name='lead_time_days',
        ),
    ]
