# Generated by Django 4.2.29 on 2026-04-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_externalorderitem_lead_time_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalorder',
            name='image',
            field=models.ImageField(blank=True, db_column='image_path', null=True, upload_to='orders/', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='externalpaymentdocument',
            name='image',
            field=models.ImageField(blank=True, db_column='image_path', null=True, upload_to='payment_documents/', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='externalreceiptdocument',
            name='image',
            field=models.ImageField(blank=True, db_column='image_path', null=True, upload_to='receipt_documents/', verbose_name='Зображення'),
        ),
    ]
