# Generated by Django 4.2.29 on 2026-04-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_externalorder_image_externalpaymentdocument_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalorder',
            name='image',
            field=models.FileField(blank=True, db_column='image_path', null=True, upload_to='orders/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='externalpaymentdocument',
            name='image',
            field=models.FileField(blank=True, db_column='image_path', null=True, upload_to='payment_documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='externalreceiptdocument',
            name='image',
            field=models.FileField(blank=True, db_column='image_path', null=True, upload_to='receipt_documents/', verbose_name='Файл'),
        ),
    ]
