# Generated by Django 4.2.29 on 2026-04-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_externalorder_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalorderitem',
            name='agreed_price',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Ціна'),
        ),
    ]
