# Generated by Django 4.2.29 on 2026-04-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_externalorderitem_agreed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalpaymentdocument',
            name='payment_amount',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Сума оплати'),
        ),
    ]
