# Generated by Django 4.2.29 on 2026-04-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_externalpaymentdocument_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalorder',
            name='prices_include_vat',
            field=models.BooleanField(default=False, verbose_name='Ціни включають ПДВ'),
        ),
    ]
