# Generated by Django 4.2.29 on 2026-04-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_externalorder_prices_include_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalorder',
            name='vat_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='Сума ПДВ'),
        ),
    ]
