# Generated by Django 4.2.29 on 2026-04-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_externalorder_vat_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalorderitem',
            name='requires_unit_conversion',
            field=models.BooleanField(default=False, verbose_name='Потребує конвертації одиниць'),
        ),
    ]
