# Generated by Django 4.2.29 on 2026-04-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_externalorderitem_requires_unit_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalreceiptdocument',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Документ завершено'),
        ),
        migrations.AddField(
            model_name='externalreceiptdocument',
            name='sent_to_warehouse',
            field=models.BooleanField(default=False, verbose_name='Передано на склад'),
        ),
    ]
