# Generated by Django 4.2.29 on 2026-04-22 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_invitem_is_splittable'),
        ('organizations', '0002_alter_organization_edrpou_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_externalreceiptdocument_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TollingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='Номер замовлення')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('active', 'Активне'), ('completed', 'Виконано')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('image', models.FileField(blank=True, db_column='image_path', null=True, upload_to='tolling_orders/', verbose_name='Файл')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tolling_orders', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tolling_orders', to='organizations.organization', verbose_name='Організація')),
            ],
            options={
                'db_table': 'tolling_orders',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TollingOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кількість')),
                ('requires_unit_conversion', models.BooleanField(default=False, verbose_name='Потребує конвертації одиниць')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Очікувана дата поставки')),
                ('inv_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tolling_order_items', to='inventory.invitem', verbose_name='Номенклатурна позиція')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.tollingorder', verbose_name='Замовлення')),
            ],
            options={
                'db_table': 'tolling_order_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TollingReceiptDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=50, unique=True, verbose_name='Номер документа приходу')),
                ('receipt_date', models.DateField(verbose_name='Дата приходу')),
                ('completed', models.BooleanField(default=False, verbose_name='Документ завершено')),
                ('sent_to_warehouse', models.BooleanField(default=False, verbose_name='Передано на склад')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('image', models.FileField(blank=True, db_column='image_path', null=True, upload_to='tolling_receipt_documents/', verbose_name='Файл')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tolling_receipt_documents', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_documents', to='orders.tollingorder', verbose_name='Замовлення')),
            ],
            options={
                'db_table': 'tolling_receipt_documents',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TollingReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Отримана кількість')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='orders.tollingorderitem', verbose_name='Рядок замовлення')),
                ('receipt_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.tollingreceiptdocument', verbose_name='Документ приходу')),
            ],
            options={
                'db_table': 'tolling_receipt_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='tollingorderitem',
            constraint=models.UniqueConstraint(fields=('order', 'inv_item'), name='uq_tolling_order_item_order_inv_item'),
        ),
    ]
