# Generated by Django 4.2.29 on 2026-05-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_externalorderevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalorderevent',
            name='event_type',
            field=models.CharField(choices=[('order_created', 'Замовлення створено'), ('order_status_changed', 'Статус замовлення змінено'), ('payment_document_created', 'Створено платіжний документ'), ('payment_document_status_changed', 'Статус платіжного документа змінено'), ('receipt_document_created', 'Створено документ приходу'), ('receipt_document_completed', 'Документ приходу завершено'), ('receipt_document_sent_to_warehouse', 'Документ приходу передано на склад'), ('comment_added', 'Додано коментар'), ('comment_updated', 'Оновлено коментар'), ('comment_deleted', 'Видалено коментар')], max_length=64, verbose_name='Тип події'),
        ),
    ]
