# Generated by Django 4.2.29 on 2026-05-18 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0014_alter_externalorderevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TollingOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_created', 'Замовлення створено'), ('order_status_changed', 'Статус замовлення змінено'), ('receipt_document_created', 'Створено документ приходу'), ('receipt_document_completed', 'Документ приходу завершено'), ('receipt_document_sent_to_warehouse', 'Документ приходу передано на склад'), ('comment_added', 'Додано коментар'), ('comment_updated', 'Оновлено коментар'), ('comment_deleted', 'Видалено коментар')], max_length=64, verbose_name='Тип події')),
                ('source', models.CharField(choices=[('tolling', 'Давальницькі замовлення'), ('logistics', 'Логістика'), ('system', 'Система')], max_length=20, verbose_name='Джерело')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(blank=True, verbose_name='Повідомлення')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Дані')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tolling_order_events', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.tollingorder', verbose_name='Давальницьке замовлення')),
            ],
            options={
                'db_table': 'tolling_order_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
