# Generated by Django 4.2.29 on 2026-05-27 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0023_alter_warehouseunitevent_operation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0015_tollingorderevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamationReturnDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(max_length=50, unique=True, verbose_name='Номер рекламації')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='draft', max_length=20, verbose_name='Статус')),
                ('return_date', models.DateField(verbose_name='Дата повернення')),
                ('reason', models.CharField(choices=[('defective_product', 'Бракована продукція'), ('procurement_error', 'Помилка у закупівлі')], max_length=30, verbose_name='Причина')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_reclamation_return_documents', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
            ],
            options={
                'db_table': 'reclamation_return_documents',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReclamationReturnDocumentLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('return_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='orders.reclamationreturndocument', verbose_name='Документ рекламації')),
            ],
            options={
                'db_table': 'reclamation_return_document_libraries',
            },
        ),
        migrations.AddField(
            model_name='externalorder',
            name='has_reclamation',
            field=models.BooleanField(default=False, verbose_name='Є рекламація'),
        ),
        migrations.AlterField(
            model_name='externalorderevent',
            name='event_type',
            field=models.CharField(choices=[('order_created', 'Замовлення створено'), ('order_status_changed', 'Статус замовлення змінено'), ('payment_document_created', 'Створено платіжний документ'), ('payment_document_status_changed', 'Статус платіжного документа змінено'), ('receipt_document_created', 'Створено документ приходу'), ('receipt_document_completed', 'Документ приходу завершено'), ('receipt_document_sent_to_warehouse', 'Документ приходу передано на склад'), ('reclamation_return_completed', 'Рекламацію завершено'), ('comment_added', 'Додано коментар'), ('comment_updated', 'Оновлено коментар'), ('comment_deleted', 'Видалено коментар')], max_length=64, verbose_name='Тип події'),
        ),
        migrations.CreateModel(
            name='ReclamationReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кількість')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.reclamationreturndocument', verbose_name='Документ рекламації')),
                ('warehouse_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamation_return_items', to='warehouse.warehouseunit', verbose_name='Складська одиниця')),
            ],
            options={
                'db_table': 'reclamation_return_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ReclamationReturnDocumentLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reclamation_return_library/')),
                ('attachment_type', models.CharField(choices=[('photo', 'Фотографія'), ('video', 'Відео')], max_length=20, verbose_name='Тип вкладення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.reclamationreturndocumentlibrary', verbose_name='Бібліотека')),
            ],
            options={
                'db_table': 'reclamation_return_document_library_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='reclamationreturndocument',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamation_returns', to='orders.externalorder', verbose_name='Замовлення'),
        ),
    ]
