# Generated by Django 4.2.29 on 2026-05-27 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0023_alter_warehouseunitevent_operation_type'),
        ('orders', '0016_reclamationreturndocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamationreturnitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamation_return_items', to='orders.externalorderitem', verbose_name='Рядок замовлення'),
        ),
        migrations.AddField(
            model_name='reclamationreturnitem',
            name='source_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamation_return_items', to='warehouse.warehouselocation', verbose_name='Локація повернення'),
        ),
        migrations.AddField(
            model_name='reclamationreturnitem',
            name='source_location_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='reclamationreturnitem',
            name='source_location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reclamationreturnitem',
            name='source_storage_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reclamation_return_items', to='warehouse.warehousestorageplace', verbose_name='Місце зберігання повернення'),
        ),
        migrations.AddField(
            model_name='reclamationreturnitem',
            name='source_storage_place_code',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='reclamationreturnitem',
            name='source_storage_place_display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reclamationreturnitem',
            name='source_storage_place_full_display',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
