# Generated by Django 4.2.29 on 2026-06-04 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0017_reclamationreturnitem_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalorderevent',
            name='event_type',
            field=models.CharField(choices=[('order_created', 'Замовлення створено'), ('order_status_changed', 'Статус замовлення змінено'), ('payment_document_created', 'Створено платіжний документ'), ('payment_document_status_changed', 'Статус платіжного документа змінено'), ('refund_document_created', 'Отримано повернення коштів'), ('receipt_document_created', 'Створено документ приходу'), ('receipt_document_completed', 'Документ приходу завершено'), ('receipt_document_sent_to_warehouse', 'Документ приходу передано на склад'), ('reclamation_return_completed', 'Рекламацію завершено'), ('comment_added', 'Додано коментар'), ('comment_updated', 'Оновлено коментар'), ('comment_deleted', 'Видалено коментар')], max_length=64, verbose_name='Тип події'),
        ),
        migrations.CreateModel(
            name='ExternalRefundDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_no', models.CharField(max_length=50, unique=True, verbose_name='Номер документа повернення коштів')),
                ('refund_amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Сума повернення')),
                ('refund_date', models.DateField(verbose_name='Дата повернення коштів')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_external_refund_documents', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_documents', to='orders.externalorder', verbose_name='Замовлення')),
            ],
            options={
                'db_table': 'external_refund_documents',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
