# Generated by Django 4.2.29 on 2026-06-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_externalorderevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalrefunddocument',
            name='file',
            field=models.FileField(blank=True, db_column='file_path', null=True, upload_to='refund_documents/', verbose_name='Файл'),
        ),
    ]
