# Generated by Django 4.2.29 on 2026-06-08 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_productattachment_is_primary_image'),
        ('orders', '0019_externalrefunddocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalOrderItemWarehouseCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кількість у замовленні')),
                ('warehouse_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кількість після складської конвертації')),
                ('line_total_amount', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Сума рядка')),
                ('cost_with_vat_per_warehouse_unit', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Собівартість складської одиниці з ПДВ')),
                ('vat_per_warehouse_unit', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='ПДВ на складську одиницю')),
                ('cost_without_vat_per_warehouse_unit', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Собівартість складської одиниці без ПДВ')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Дата розрахунку')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_order_warehouse_costs', to='inventory.invitem', verbose_name='Складська номенклатура')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_costs', to='orders.externalorder', verbose_name='Замовлення')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_cost', to='orders.externalorderitem', verbose_name='Рядок замовлення')),
            ],
            options={
                'db_table': 'external_order_item_warehouse_costs',
                'ordering': ['order_id', 'order_item_id'],
            },
        ),
    ]
