# Generated by Django 4.2.29 on 2026-06-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_productattachment_is_primary_image'),
        ('orders', '0020_externalorderitemwarehousecost'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderIntakeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_flow', models.CharField(choices=[('procurement', 'Закупівля'), ('tolling', 'Давальницьке замовлення')], max_length=20, verbose_name='Сценарій надходження')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_intake_documents',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='externalreceiptdocument',
            name='use_new_scenario',
            field=models.BooleanField(default=False, verbose_name='Використовувати новий сценарій приймання'),
        ),
        migrations.CreateModel(
            name='OrderIntakeDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Кількість у документі приходу')),
                ('requires_unit_conversion', models.BooleanField(default=False, verbose_name='Потребує конвертації одиниць')),
                ('external_receipt_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_item', to='orders.externalreceiptitem', verbose_name='Рядок приходу закупівлі')),
                ('intake_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.orderintakedocument', verbose_name='Документ приймання')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_intake_items', to='inventory.invitem', verbose_name='Номенклатура')),
            ],
            options={
                'db_table': 'order_intake_document_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='orderintakedocument',
            name='external_receipt_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_document', to='orders.externalreceiptdocument', verbose_name='Документ приходу закупівлі'),
        ),
    ]
