# Generated by Django 4.2.29 on 2026-06-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_orderintakedocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderintakedocument',
            name='status',
            field=models.CharField(choices=[('created', 'Створено'), ('executed', 'Оброблено складом'), ('rollover', 'Скасовано через відкат'), ('reclamation', 'Скасовано через рекламацію'), ('refusal', 'Відмова складу')], default='created', max_length=20, verbose_name='Статус'),
        ),
    ]
