# Generated by Django 4.2.29 on 2026-06-15 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_orderintakedocument_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderintakedocument',
            name='tolling_receipt_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_document', to='orders.tollingreceiptdocument', verbose_name='Документ приходу давальницького замовлення'),
        ),
        migrations.AddField(
            model_name='orderintakedocumentitem',
            name='tolling_receipt_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intake_item', to='orders.tollingreceiptitem', verbose_name='Рядок приходу давальницького замовлення'),
        ),
        migrations.AddField(
            model_name='tollingreceiptdocument',
            name='use_new_scenario',
            field=models.BooleanField(default=False, verbose_name='Використовувати новий сценарій приймання'),
        ),
    ]
