# Generated by Django 4.2.29 on 2026-06-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_orderintakedocument_tolling_receipt_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollingorder',
            name='use_new_scenario',
            field=models.BooleanField(default=False, verbose_name='Використовувати новий сценарій приймання'),
        ),
    ]
