# Generated by Django 4.2.29 on 2026-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_tollingorder_use_new_scenario'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderintakedocument',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('external_receipt_document__isnull', False), ('source_flow', 'procurement'), ('tolling_receipt_document__isnull', True)), models.Q(('external_receipt_document__isnull', True), ('source_flow', 'tolling'), ('tolling_receipt_document__isnull', False)), _connector='OR'), name='ck_order_intake_document_single_source'),
        ),
        migrations.AddConstraint(
            model_name='orderintakedocumentitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('external_receipt_item__isnull', False), ('tolling_receipt_item__isnull', True)), models.Q(('external_receipt_item__isnull', True), ('tolling_receipt_item__isnull', False)), _connector='OR'), name='ck_order_intake_document_item_single_source'),
        ),
    ]
