# Generated by Django 4.2.29 on 2026-05-04 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_edrpou_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0009_invitem_is_splittable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Чернетка'), ('confirmed', 'Підтверджено'), ('in_progress', 'В роботі'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL, verbose_name='Створено користувачем')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='organizations.organization', verbose_name='Організація')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='inventory.product', verbose_name='Виріб')),
            ],
            options={
                'db_table': 'sales_orders',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('source_type', models.CharField(choices=[('stock', 'Склад'), ('customer', 'Від замовника'), ('donated', 'Донорський')], max_length=20)),
                ('inv_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_components', to='inventory.invitem')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='sales.salesorder')),
                ('source_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provided_sales_order_components', to='organizations.organization')),
            ],
            options={
                'db_table': 'sales_order_components',
                'ordering': ['sales_order', 'id'],
            },
        ),
    ]
