# Generated by Django 4.2.29 on 2026-05-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('confirmed', 'Підтверджено'), ('in_progress', 'В роботі'), ('ready', 'Готово до передачі'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
