# Generated by Django 4.2.29 on 2026-05-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_salesorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата виконання'),
        ),
    ]
