# Generated by Django 4.2.29 on 2026-05-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salesorder_completed_at'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="salesordercomponent",
                    name="is_required_for_start",
                    field=models.BooleanField(default=True),
                ),
            ],
        ),
    ]