# Generated by Django 4.2.29 on 2026-05-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_person_rank_person_rank_force_type'),
        ('sales', '0004_salesordercomponent_is_required_for_start'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="salesorder",
                    name="customer_responsible_person",
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="responsible_sales_orders", to="organizations.person", verbose_name="Відповідальна особа замовника"),
                ),
            ],
        ),
    ]
