# Generated by Django 4.2.29 on 2026-05-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesorder_customer_responsible_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesordercomponent',
            name='source_organization',
        ),
        migrations.RemoveField(
            model_name='salesordercomponent',
            name='source_type',
        ),
        migrations.AddField(
            model_name='salesordercomponent',
            name='fulfillment_mode',
            field=models.CharField(choices=[('customer', 'Від замовника'), ('mixed', 'Комбіновано')], default='mixed', max_length=20),
        ),
    ]
