# Generated by Django 4.2.29 on 2026-05-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_salesordercomponent_source_organization_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salesordercomponent',
            constraint=models.UniqueConstraint(fields=('sales_order', 'inv_item'), name='uq_sales_order_component_sales_order_inv_item'),
        ),
    ]
