# Generated by Django 4.2.29 on 2026-05-11 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_invitem_is_required_for_production_start_and_more'),
        ('sales', '0007_salesordercomponent_uq_sales_order_component_sales_order_inv_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('confirmation', 'Підтвердження'), ('production_start', 'Запуск виробництва'), ('production_execution', 'Виконання виробництва')], max_length=32)),
                ('issue_type', models.CharField(choices=[('customer_component_missing', 'Відсутній товар замовника'), ('mixed_component_missing', 'Відсутній mixed-компонент')], max_length=64)),
                ('status', models.CharField(choices=[('open', 'Відкрита'), ('resolved', 'Вирішена'), ('ignored', 'Проігнорована')], default='open', max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Критична'), ('non_critical', 'Некритична')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('missing_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('related_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='sales.salesordercomponent')),
                ('related_inv_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_issues', to='inventory.invitem')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='sales.salesorder')),
            ],
            options={
                'db_table': 'sales_order_issues',
                'ordering': ['sales_order', 'stage', 'id'],
            },
        ),
    ]
