# Generated by Django 4.2.29 on 2026-05-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salesorderissue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesordercomponent',
            name='is_required_for_start',
        ),
    ]
