# Generated by Django 4.2.29 on 2026-05-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_productiondiaryentry_productiondiaryattachment'),
        ('sales', '0009_remove_salesordercomponent_is_required_for_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderissue',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='production.productionorder'),
        ),
        migrations.AddField(
            model_name='salesorderissue',
            name='production_order_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='production.productionorderstep'),
        ),
        migrations.AddField(
            model_name='salesorderissue',
            name='production_order_step_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='production.productionorderstepcomponent'),
        ),
    ]
