# Generated by Django 4.2.29 on 2026-05-14 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0010_salesorderissue_production_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderissue',
            name='issue_type',
            field=models.CharField(choices=[('customer_component_missing', 'Відсутній товар замовника'), ('mixed_component_missing', 'Відсутній mixed-компонент'), ('step_component_missing', 'Відсутній компонент етапу')], max_length=64),
        ),
        migrations.AlterField(
            model_name='salesorderissue',
            name='stage',
            field=models.CharField(choices=[('confirmation', 'Підтвердження'), ('production_start', 'Запуск виробництва'), ('production_step_confirmation', 'Підтвердження етапу'), ('production_execution', 'Виконання виробництва')], max_length=32),
        ),
        migrations.CreateModel(
            name='SalesOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sales_order_created', 'SalesOrder створено'), ('sales_order_details_updated', 'Оновлено деталі SalesOrder'), ('sales_order_confirmed', 'SalesOrder підтверджено'), ('production_order_created', 'Створено ProductionOrder'), ('sales_order_cancelled', 'SalesOrder скасовано'), ('production_order_cancelled', 'ProductionOrder скасовано')], max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_events', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sales.salesorder')),
            ],
            options={
                'db_table': 'sales_order_events',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
