# Generated by Django 4.2.29 on 2026-05-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_salesorderissue_issue_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderevent',
            name='source',
            field=models.CharField(choices=[('sales', 'Продажі'), ('production', 'Виробництво'), ('warehouse', 'Склад'), ('system', 'Система')], default='system', max_length=20),
            preserve_default=False,
        ),
    ]
