# Generated by Django 4.2.29 on 2026-05-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_salesorderevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderevent',
            name='event_type',
            field=models.CharField(choices=[('sales_order_created', 'SalesOrder створено'), ('sales_order_details_updated', 'Оновлено деталі SalesOrder'), ('sales_order_confirmed', 'SalesOrder підтверджено'), ('production_order_created', 'Створено ProductionOrder'), ('sales_order_cancelled', 'SalesOrder скасовано'), ('production_order_cancelled', 'ProductionOrder скасовано'), ('production_diary_entry_created', 'Додано запис у щоденник'), ('production_diary_entry_updated', 'Оновлено запис щоденника'), ('production_diary_entry_deleted', 'Видалено запис щоденника'), ('production_order_step_confirmed', 'Підтверджено етап виробництва'), ('production_order_started', 'Виробництво запущено'), ('production_movement_invoice_generated', 'Сформовано накладну видачі у виробництво'), ('production_movement_executed', 'Компоненти передано у виробництво')], max_length=64),
        ),
    ]
