# Generated by Django 4.2.29 on 2026-06-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_salesorderevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закриття'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата готовності'),
        ),
    ]
